# config for kibana
server.name: kibana
# 허용할 호스트
# "0" : 모든 호스트 허용
server.host: "0.0.0.0"
# ES 연결
elasticsearch.hosts: http://elasticsearch:9201
elasticsearch.username: "admin"
elasticsearch.password: ""